

export const DATA_FROM_SEARCH = "DATA_FROM_SEARCH"

export const ADD_TO_CART = "ADD_TO_CART"
export const GET_SELLERS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_SELLERS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_SELLERS_ERROR = "GET_PRODUCTS_ERROR";

