
export const ADD_TO_CART = "ADD_TO_CART"
export const GET_SELLERS_BEGIN = "GET_SELLERS_BEGIN";
export const GET_SELLERS_SUCCESS = "GET_SELLERS_SUCCESS";
export const GET_SELLERS_ERROR = "GET_SELLERS_ERROR";
export const DATA_FROM_SEARCH = "DATA_FROM_SEARCH";
export const GET_PRODUCTID_BEGIN = "GET_PRODUCTID_BEGIN";
export const GET_PRODUCTID_SUCCESS = "GET_PRODUCTID_SUCCESS";
export const GET_PRODUCTID_ERROR = "GET_PRODUCTID_ERROR";
